discord:
  token: ""      # bot token (apparently you are not supposed to post this one online)
  channel_id: ""  # ID of Discord channel to mirror into MC

whitelist:
  enabled: false
  kick_on_disconnect: false #only valid if whitelist is enabled

format: #todo reduce
  minecraftChat: #text format with minimessage https://docs.advntr.dev/minimessage
    serverJoin:
      whitelistRejection: ""
      notReadyRejection: ""
    messages:
      pluginEnable: "ChatBridge Enabled!"
      pluginDisable: "ChatBridge Disabled!"
      serverMsg: "<yellow><message></yellow>" #todo customize different kinds
      linkedMsg: "<blue>[D]</blue> <<sender>> <message>"
      unlinkedMsg: "<blue>[D]</blue> @<sender>: <message>" #eg
    commands:
      connect:
        description: ""
        args: ""
        response:
          missing_userArg: ""
      disconnect:
        description: ""
      status:
        description: ""
        response:
          linked: "" #<uuid><mcname><dcid><dcname>
          not_linked: ""
          linked_toDc: "" #<dcname><dcid>
          linked_fromDc: "" #<dcclaims>
          linked_fromBothNoMatch: "" #<dcclaims><dcname><dcid>
  discordChat:
    server_online_status: ""
    messages:
      join: ""
      leave: ""
      pluginEnable: ""
      pluginDisable: ""
    commands:
      error_reply: "" # %s -> error
      connect:
        description: ""
        arg_description: ""
        response:
          resolve_error: "" # %s -> uuid that wasn't resolved
          missing_playerArg: ""
      disconnect:
        description: ""
      status:
        description: ""
        response: "" # ....