discord:
  token: ""      # bot token (apparently you are not supposed to post this one online)
  channel_id: ""  # ID of Discord channel to mirror into MC

whitelist:
  enabled: false

format: #todo reduce #text format with minimessage https://docs.advntr.dev/minimessage
  serverJoin:
    whitelistRejection: ""
    notReadyRejection: ""
  minecraftChat:
    messages:
      pluginEnable: ""
      pluginDisable: ""
    commands:
      connect:
        description: ""
        args: ""
        response: ""
      disconnect:
        description: ""
        args: ""
        response: ""
      status:
        description: ""
        args: ""
        response:
          linked: "" #<uuid><mcname><dcid><dcname>
          not_linked: ""
          linked_toDc: "" #<mcname><uuid>
          linked_fromDc: "" #<dcclaims>
          linked_fromBothNoMatch: "" #<dcclaims><mcname><uuid>
  discordChat:
    server_online_status: ""
    messages:
      join: ""
      leave: ""
      pluginEnable: ""
      pluginDisable: ""
    commands:
      error_reply: "" # %s -> error
      connect:
        description: ""
        arg_description: ""
        response:
          resolve_error: "" # %s -> uuid that wasn't resolved
          missing_playerArg: ""
      disconnect:
        description: ""
        response: ""
      status:
        description: ""
        response: ""
