discord:
  token: ""      # bot token (apparently you are not supposed to post this one online)
  channel_id: ""  # ID of Discord channel to mirror into MC

sendConnectionReminder: true

whitelist:
  enabled: false
  kick_on_disconnect: false #only valid if whitelist is enabled

format:
  minecraftChat: #text format with minimessage https://docs.advntr.dev/minimessage
    avatarApi: "https://mc-heads.net/avatar/%s/128" # %s -> player UUID
    disconnectKickMsg: "Your account is no longer associated with a discord account.\nRun /connect in Discord."
    serverJoin:
      whitelistRejection: "Your account is not associated with a discord account yet.\nJoin our Discord and run /connect first."
      loginUnavailableRejection: "Login system is temporarily unavailable. Try again in a moment or contact Server Admin."
    messages:
      pluginEnabled: "ChatBridge Enabled!"
      pluginDisabled: "ChatBridge Disabled!"
      serverMsg: "<yellow><message></yellow>"
      linkedMsg: "<hover:show_text:'@<senderdc>'><blue>[D]</blue></hover> <<sender>> <message>"
      unlinkedMsg: "<blue>[D]</blue> @<sender>: <message>"
      connectionReminder: "Use /connect to link your Discord account now!"
    commands:
      error_reply: "Error: %s" # %s -> error msg
      connect:
        description: "Link to a Minecraft account"
        arg_description: "Minecraft UUID or player name"
      disconnect:
        description: "Remove your Discord→MC claim"
      status:
        description: "Show your link status"
        response:
          unlinked: "<red>❕ Not linked</red>\n<gray>Use /connect to link (for comfort do it on discord first)</gray>"
          linked: "<green>✅ Linked to <hover:show_text:'<dcid>'><dcname></hover></green>" #<dcid><dcname>
          linked_toDc: "<yellow>❕ Not linked yet</yellow>\n<gray>You are currently claiming <hover:show_text:'<dcid>'><dcname></hover>\nUse /connect in discord to complete the link.</gray>" #<dcid><dcname>
          linked_fromDc: "<yellow>❕ Not linked yet</yellow>\n<gray>Your account is currently being claimed by: [<dcclaims>]\nUse /connect to complete a link.</gray>" #<dcclaims>
          linked_fromBothNoMatch: "<>❕Not linked</yellow>\n<gray>You are currently claiming <hover:show_text:'<dcid>'><dcname></hover>\nYour account is currently being claimed by: [<dcclaims>]\nUse /connect at any time on either end to update your claims.</gray>" #<dcclaims><dcid><dcname>

  discordChat:
    server_online_status: "Server Online!"
    messages:
      join: "`➕` **%s** joined the server" # %s -> player
      leave: "`➖` **%s** left the server" # %s -> player
      pluginEnabled: "`🟢` **ChatBridge enabled**"
      pluginDisabled: "`🔴` **ChatBridge disabled**"
    commands: #if you set the commands to have the same name you can go fuck yourself
      error_reply: "❌ Error: %s" # %s -> error
      connect:
        name: "connect"
        description: "Link to a Minecraft account"
        arg_name: "player"
        arg_description: "Minecraft UUID or player name"
        response:
          resolving_status: "Resolving Player Name to UUID..."
          resolve_error:
            reason_notExist: "'%s' does not seem to be a player. Check for typos or enter your UUID directly." # %s -> name that wasn't resolved
            reason_api: "Could not Resolve name to an UUID due to API problems. Try again later or enter your UUID directly."
            reason_other: "Could not Resolve name to an UUID for an unspecified reason. Cry about it."
      disconnect:
        name: "disconnect"
        description: "Remove your Discord→MC claim"
      status:
        name: "status"
        description: "Show your link status"
        response:
          title: "Connection status"
          linked: "✅ Your Discord is **linked** to this Minecraft account."
          not_linked: "❕ Your Discord is **not linked** yet."
          info_field:
            title: "Claimed Minecraft UUID"
            content: "[%s]" # %s -> player uuid
          instruction_field:
            complete:
              title: "How to link"
              content: "Use `/connect <mc-uuid or name>`."
            minecraft:
              title: "Next step"
              content: "Run **/connect %s** in Minecraft to confirm. (autocompletes)" # %s -> user id
