name: ChatBridge
version: '1.1'
main: com.mhgandhi.chatBridge.ChatBridge
api-version: '1.21'
commands:
  connect:
    description: Mirror your Minecraft Chat into Discord and back and link identities!
    usage: /connect <discord-id> (do it in discord first)
    permission: chatbridge.connect
  disconnect:
    description: Remove your MC→Discord claim
    usage: /disconnect
    permission: chatbridge.disconnect
  status:
    description: Show your link status
    usage: /disconnect
    permission: chatbridge.status
permissions:
  chatbridge.*:
    default: true
    children:
      chatbridge.connect: true
      chatbridge.disconnect: true
      chatbridge.status: true
