name: ChatBridge
version: '1.0'
main: com.mhgandhi.chatBridge.ChatBridge
api-version: '1.21'
commands:
  connect:
    description: Link your MC account to a Discord account
    usage: /<command> [discord-id-or-name]
    permission: chatbridge.connect
  disconnect:
    description: Remove your MC→Discord claim
    usage: /<command>
    permission: chatbridge.disconnect
  status:
    description: Show your link status
    usage: /<command>
    permission: chatbridge.status
permissions:
  chatbridge.*:
    default: true
    children:
      chatbridge.connect: true
      chatbridge.disconnect: true
      chatbridge.status: true
